version: '3'
services:
  webspring-mysql:
    image: webspring-mysql:latest
    container_name: webspring-prod
    ports:
    - 3317:3306
    environment:
    - MYSQL_ROOT_PASSWORD=root
    - MYSQL_DATABASE=dinerapp
  webspring:
    image: webspring:latest
    depends_on:
    - webspring-mysql
    ports:
    - 5554:8080
    environment:
    - SPRING_DATASOURCE_URL=jdbc:mysql://webspring-mysql/webSpring?verifyServerCertificate=false&useSSL=true
    - SPRING_DATASOURCE_USERNAME=root
    - SPRING_DATASOURCE_PASSWORD=root