version: '3'
services:      
  webspring:
    image: webspring:latest
    external_links:
      - dinerapp-prod
    ports:
      - 5554:8080
    environment:
      - SPRING_DATASOURCE_URL=jdbc:mysql://localhost:3307/webSpring?useSSL=false
      - SPRING_DATASOURCE_USERNAME=root
      - SPRING_DATASOURCE_PASSWORD=root
      
