version: '3'

services:
  springweb-mysql: 
    image: custom-mysql-img:latest
    container_name: w-prod
    ports:
      - 3313:3306
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=dinerapp
      
  spring-boot-jpa-docker-springweb:
    image: springweb-img:latest
    depends_on:
      - springweb-mysql
    ports:
      - 5554:8080
    environment:
      - SPRING_DATASOURCE_URL=jdbc:mysql://docker-mysql/webSpring?verifyServerCertificate=false&useSSL=true
      - SPRING_DATASOURCE_USERNAME=root
      - SPRING_DATASOURCE_PASSWORD=root
