version: '3'
services:
  webspring-mysql:
    image: mysql:8.0
    container_name: custom-mysql-img
    ports:
      - 3317:3306
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=dinerapp
  webspring:
    image: webspring:latest
    depends_on:
    - webspring-mysql
    ports:
    - 5554:8080
    environment:
    - SPRING_DATASOURCE_URL=jdbc:mysql://dinerapp/webSpring?verifyServerCertificate=false&useSSL=true
    - SPRING_DATASOURCE_USERNAME=root
    - SPRING_DATASOURCE_PASSWORD=root