version: '3'
services:      
  webspring:
    image: webspring:latest
    external_links:
      - dinerapp-prod
    ports:
      - 5554:8080
    environment:
      - SPRING_DATASOURCE_URL=jdbc:mysql://dinerapp-prod/webSpring?useSSL=false
      - SPRING_DATASOURCE_USERNAME=root
      - SPRING_DATASOURCE_PASSWORD=root
networks:
  default:
    external: 
      name: dinerapp_bridge
    