version: '3'

services: 
  docker-mysql:
    image: custom-mysql-img:latest
    container_name: webSpring-prod
    ports:
      - 3307:3306
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=webSpring
  spring-boot-jpa-docker-webapp:
    image: dinerapp-img:latest
    depends_on:
      - docker-mysql
    ports:
      - 5432:8080
    environment:
      - SPRING_DATASOURCE_URL=jdbc:mysql://docker-mysql/webSpring?verifyServerCertificate=false&useSSL=true
      - SPRING_DATASOURCE_USERNAME=root
      - SPRING_DATASOURCE_PASSWORD=root
