version: '3'

services: 
  spring-boot-jpa-docker-webspring:
    image: webspring-img:latest
    ports:
      - 5431:8080
    environment:
      - SPRING_DATASOURCE_URL=jdbc:mysql://docker-mysql/webSpring?verifyServerCertificate=false&useSSL=true
      - SPRING_DATASOURCE_USERNAME=root
      - SPRING_DATASOURCE_PASSWORD=root
